name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  compile:
    name: Check compiler errors
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
          cache: 'npm'
      - name: install deps
        run: npm install
      - name: build
        run: npm run build

